### ISSUE TITLE
Build error when building for Apple Silicon (Universal binary)

### ISSUE THREAD

**Issue by bpresles** [apache/cordova-osx#104]
# Bug Report

## Problem

Building Cordova OS X app for Apple Silicon (Universal Binary for both Intel x86_64 and arm64) fails.

### What is expected to happen?

Build fine.

### What does actually happen?

The compiler reports an issue with objc_msgSend() calls : "Too many arguments to function call, expected 0, have 3"

Used on the following files:

CordovaLib/Classes/CDVBridge.m line 77 (on latest master code)
CordovaLib/Classes/Commands/CDVCommandQueue.m line 146 (on latest master code)

## Information

This is caused by the fact that old prototype were deprecated and are now not supported at all on Apple Silicon Macs.

To solve that issue, either use new prototype with casting:

```objc
void* (*msgSend)(id, SEL, CDVInvokedUrlCommand*) = (typeof(msgSend)) &objc_msgSend;
msgSend(obj, normalSelector, command);
```
Or use 

```objc
[obj performSelector:normalSelector withObject:command];
```

### Command or Code

Use Xcode 12 Beta for Universal Apps and build with target "Any Mac (Apple Silicon, Intel)"

### Environment, Platform, Device

iMac Intel Core i7 under macOS 10.15.5 Catalina with XCode 12 Beta for Universal Apps.

### Version information

Cordova OS X 6.0 with Ionic 1.3.5.
macOS Catalina 10.15.5
Xcode 12 Beta for Universal Apps.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by rchrd2** [comment]
This fork fixed a compiling issue for me.

**Comment by qpwr** [comment]
Is this ever going to be merged? Is the cordova-osx repository still maintained at all?

**Comment by brodybits** [comment]
I highly recommend that you followup on Slack and on the dev mailing list, please follow links from the footer of cordova.io or cordova.apache.org, and try again if you don't hear anything. Unfortunately the maintainers have been pretty overloaded over the past couple years.

**Comment by fortuna** [comment]
See also: https://github.com/apache/cordova-osx/issues/112
