### ISSUE TITLE
build issue with Xcode 12.2

### ISSUE THREAD

**Issue by SebastienDevAccount** [apache/cordova-osx#109]
I have Xcode Version 12.2 (12B45b).
I typed:

MacBook-Pro-15-de-Sebastien-2:Desktop sd$ cordova create test
Creating a new cordova project.
MacBook-Pro-15-de-Sebastien-2:Desktop sd$ cd test
MacBook-Pro-15-de-Sebastien-2:test sd$ cordova platform add osx
Using cordova-fetch for cordova-osx@^6.0.0
Adding osx project...
OS X project created with cordova-osx@6.0.0
Discovered plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for osx
Adding cordova-plugin-whitelist to package.json
MacBook-Pro-15-de-Sebastien-2:test sd$ cordova build osx

...

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target arm64-apple-macos10.9 -fmessage-length\=189 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fcolor-diagnostics -std\=gnu99 -fobjc-arc -fmodules -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/var/folders/zr/z51y19890vd7wqmnpwj5w9_40000gn/C/org.llvm.clang/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -iquote /Users/sd/Desktop/test/platforms/osx/CordovaLib/build/CordovaLib.build/Debug/Cordova.build/Cordova-generated-files.hmap -I/Users/sd/Desktop/test/platforms/osx/CordovaLib/build/CordovaLib.build/Debug/Cordova.build/Cordova-own-target-headers.hmap -I/Users/sd/Desktop/test/platforms/osx/CordovaLib/build/CordovaLib.build/Debug/Cordova.build/Cordova-all-target-headers.hmap -iquote /Users/sd/Desktop/test/platforms/osx/CordovaLib/build/CordovaLib.build/Debug/Cordova.build/Cordova-project-headers.hmap -I/Users/sd/Desktop/test/platforms/osx/build/include -I/Users/sd/Desktop/test/platforms/osx/build/usr/local/lib/include -I/Users/sd/Desktop/test/platforms/osx/CordovaLib/build/UninstalledProducts/include -I/Users/sd/Desktop/test/platforms/osx/CordovaLib/build/UninstalledProducts/macosx/include -I/Users/sd/Desktop/test/platforms/osx/build -I/Users/sd/Desktop/test/platforms/osx/CordovaLib/build/CordovaLib.build/Debug/Cordova.build/DerivedSources-normal/arm64 -I/Users/sd/Desktop/test/platforms/osx/CordovaLib/build/CordovaLib.build/Debug/Cordova.build/DerivedSources/arm64 -I/Users/sd/Desktop/test/platforms/osx/CordovaLib/build/CordovaLib.build/Debug/Cordova.build/DerivedSources -F/Users/sd/Desktop/test/platforms/osx/build -include /Users/sd/Desktop/test/platforms/osx/build/sharedpch/SharedPrecompiledHeaders/2373811082599241398/CordovaLib-Prefix.pch -MMD -MT dependencies -MF /Users/sd/Desktop/test/platforms/osx/CordovaLib/build/CordovaLib.build/Debug/Cordova.build/Objects-normal/arm64/CDVCommandQueue.d --serialize-diagnostics /Users/sd/Desktop/test/platforms/osx/CordovaLib/build/CordovaLib.build/Debug/Cordova.build/Objects-normal/arm64/CDVCommandQueue.dia -c /Users/sd/Desktop/test/platforms/osx/CordovaLib/CordovaLib/Classes/Commands/CDVCommandQueue.m -o /Users/sd/Desktop/test/platforms/osx/CordovaLib/build/CordovaLib.build/Debug/Cordova.build/Objects-normal/arm64/CDVCommandQueue.o
/Users/sd/Desktop/test/platforms/osx/CordovaLib/CordovaLib/Classes/Commands/CDVCommandQueue.m:146:22: error: too many arguments to function call, expected 0, have 3
        objc_msgSend(obj, normalSelector, command);
        ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~


...


warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no run destination to provide an active architecture; building for all applicable architectures (in target 'Cordova' from project 'CordovaLib')
** BUILD FAILED **

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by SebastienDevAccount** [comment]
I sometimes wonder if you are testing what you are developing.

**Comment by qpwr** [comment]
@SebastienDevAccount, did you solve the issue?
