### ISSUE TITLE
App crashes on macOS 11 Big Sur with __CRASHING_DUE_TO_PRIVACY_VIOLATION__

### ISSUE THREAD

**Issue by qpwr** [apache/cordova-osx#110]
This is rather no bug report, but I'm trying to help others who stumble upon the same issue. My app with cordova-osx 6.0.0 works perfectly fine on macOS 10, but crashed on macOS 11 (Big Sur). The error report contained the __CRASHING_DUE_TO_PRIVACY_VIOLATION__ flag, which is why I assumed the issue could be due to missing NS*UsageDescription strings in the *-Info.plist file (similar to when iOS made them mandatory).

After I included the needed strings, the app worked as expected. This is what I added to my config.xml

```
    <platform name="osx">
        <!-- other stuff which is not relevant for this topic -->
        <config-file parent="NSBluetoothAlwaysUsageDescription" platform="osx" target="*-Info.plist">
            <string>Reason why this app needs bluetooth goes here.</string>
        </config-file>
        <config-file parent="NSBluetoothPeripheralUsageDescription" platform="osx" target="*-Info.plist">
            <string>Reason why this app needs periphals goes here</string>
        </config-file>
        <config-file parent="NSCameraUsageDescription" platform="osx" target="*-Info.plist">
            <string>Reason why this app needs the camera goes here</string>
        </config-file>
    </platform>
```

Hopefully someone will find this useful.

**Comment by brodybits** [comment]
Thanks for reporting. This looks like it needs to be documented. A minimal reproduction would increase the chance of getting help from the maintainers.

I would also highly recommend that you followup on Slack and on the dev mailing list, please follow links from the footer of cordova.io or cordova.apache.org, and try again if you don't hear anything. Unfortunately the maintainers have been pretty overloaded over the past couple years.

**Comment by NiklasMerz** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
