### ISSUE TITLE
Use NSOperationQueue to resolve possible concurrency issue on macOS

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-osx#70]
Similar to issue discussed for iOS in apache/cordova-ios#452, with PR proposed in for iOS in apache/cordova-ios#454

**Comment by NiklasMerz** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
