### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by janpio** [apache/cordova-osx#71]
Travis is configured, but doesn't seem to actually run the tests.

**Comment by brodybits** [comment]
@janpio how can we send this to INFRA? I am not able to activate it on this project.

**Comment by janpio** [comment]
Create a JIRA issue in the INFRA project. (You will probably want to look for older issues that requested Travis/AppVeyor integration to find out what they usually want to know/see when getting such tickets.)

**Comment by brodybits** [comment]
I just raised <https://issues.apache.org/jira/browse/INFRA-17331>.

FYI the active 4.0.3 & master branches show green builds on my fork.

**Comment by brodybits** [comment]
Travis CI is now activated, PR #73 is now green after rebase.

Looks like we got a badge in <https://api.travis-ci.org/apache/cordova-osx.svg?branch=master>.

**Comment by janpio** [comment]
https://apache.github.io/cordova-status/ / https://github.com/apache/cordova-status already shows that badge 🥇
