### ISSUE TITLE
Method nativeEvalAndFetch(function(){%@}) missing in exec.js

### ISSUE THREAD

**Issue by tomasszabo** [apache/cordova-osx#80]
In a Cordova plugin for OSX platform I'm calling following method on `CDVCommandDelegate`

    - (void) evalJs:(NSString*) js

which in fact executes Javascript:

    cordova.require('cordova/exec').nativeEvalAndFetch(...)

Problem is that method `nativeEvalAndFetch` is not defined in `cordova/exec` module (defined in `exec.js`) and therefore not available in runtime.

I've manually added following implementation

    OSXExec.nativeEvalAndFetch = function(func) {
        func();
    };

however, I'm not sure if it's fully compatible with OSX Cordova platform implementation.

Method `nativeEvalAndFetch` exists in `exec.js` of iOS Cordova platform implementation, so possibly this is a portation problem.

---

Node version: v10.8.0
Cordova version: 8.1.1
`<engine name="osx" spec="^4.0.2" />`

**Comment by brodybits** [comment]
Thanks for reporting, I just added the **bug** label. Should be an easy fix (see j3k0/cordova-plugin-purchase#848) if someone has time to make and test it.

One more thing: I have a *feeling* (just a feeling right now) that it should be possible to make a more general solution in cordova-js.

**Comment by NiklasMerz** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
