### ISSUE TITLE
Use cross-spawn ("superspawn"); fix xcodebuild command log; deprecate spawn.js

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-osx#81]
As proposed and discussed in apache/cordova-ios#478 / apache/cordova-ios#479 / apache/cordova-ios#481

**Comment by NiklasMerz** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
