### ISSUE TITLE
Help : Cannot get Geolocation 

### ISSUE THREAD

**Issue by ameykshirsagar** [apache/cordova-osx#84]
Hi,
I am trying to build a map app for Mac OSX desktop for which I require accessing geolocation. However I tried to get one but it didn't work. I am getting an error code :1 i.e Permission denied to access geolocation. I tried adding following entries to Info.plist file 
`
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>Need Location access</string>
    <key>NSLocationUsageDescription</key>
    <string>Location acccess Desc</string>
`
Still I am getting no prompt that asks for giving access to geolocation permission. Can anyone help me with this??

Thanks

**Comment by NiklasMerz** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
