### ISSUE TITLE
Access menu-items

### ISSUE THREAD

**Issue by tiptronic** [apache/cordova-osx#94]
Are there any intentions to add menubar (or menu-item) support for `osx` and `windows` targets?

Reason is: Cordova-osx is a pretty good shell to (quickly) spawn desktop-applications or desktop-prototypes using the same code as their mobile counterparts.
Simply some infrastructure support is lacking (e.g. menubar, menu-item support).

If that's not planned: 
What would I need to do to 
- enable e.g. `Copy`, `Paste`,  menu-items to call call into my Javascript, or 
- allow me to keep my `document.addEventListener('paste', ...)`) in Javascript code?

**Comment by qpwr** [comment]
Are there any plans to add this? Apple actually rejected my app due to issues with missing menu bar items. This is what they said:

> The user interface of your app is not consistent with the macOS Human Interface Guidelines.
> Specifically, we found that when the user closes the main application window there is no menu item to re-open it.

Also they complained about the preference menu item which doesn't work:

> We discovered one or more bugs in your app when reviewed on Mac running macOS 10.15.6.
> App Menu > Preferences does not appear to work.

It seems that the 'preference' entry is always there and I didn't find a way to either disable it or make it useful. You can click it, but nothing happens (which is expectable).

**Comment by tiptronic** [comment]
@qpwr Agree - that would be pretty important in this case... Right now, you have do go the Cordova/Electron route, which add a sloppy 100MB to your application size (and is not even closely as fast as a regular Cordova app).

So again: +1

**Comment by qpwr** [comment]
Well, for now you can just adapt the ```MainViewController.xib``` (within the osx platform folder of your project) file to you needs, which is exactly what I did. I removed most of the menu items and only left those which are really needed. An voila, my app passed the review.

**Comment by tiptronic** [comment]
Jep - but you can't add menu-items that way easily (not to think about localized ones) ;)

**Comment by bamboolix** [comment]
Same app submission refusal on my side for instance.

**Comment by NiklasMerz** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
